### ISSUE TITLE
Save Har file to the file with getHar(), but failed to validate Har file

### ISSUE THREAD

**Issue by joychester** [alexbardas/nightmare-har-plugin#1]
Hi, there, 
by nightmare-har-plugin to generate a Har file: 

> 
>   yield nightmare
>     .viewport(1300, 1000)
>     .waitForDevtools()
>     .wait(RENDER_TIME_MS);
> 
>   yield nightmare
>     .goto(url)
>     .wait(1000);
> 
>   yield nightmare
>       .wait(RENDER_TIME_MS)
>       .getHAR()
>       .end()
>       .then( function(result) {
>           console.log("end of the test: " + Date.now());
>           //save to file to sample.har file
>           fs.writeFileSync('sample.har', JSON.stringify(result));
>       });

using har viewer to validate the generated Har file failed: 
http://www.softwareishard.com/har/viewer/
or 
https://micmro.github.io/PerfCascade/

a sample har file for further analysis:
[sample.har.txt](https://github.com/alexbardas/nightmare-har-plugin/files/792406/sample.har.txt)

**Comment by alexbardas** [comment]
Thanks for noticing this, @joychester.

Doing `fs.writeFileSync('sample.har', JSON.stringify({log: result}));` instead generates a file that can be visualised in both tools. (the har needs the extra `log` namespace).

I'll update the documentation to specify this.

**Comment by alexbardas** [comment]
I've updated the Readme and I'll close this issue.

Please let me know if there is still something that doesn't work.

**Comment by joychester** [comment]
@alexbardas , let me validate on my side, Thanks a lot for your help, nice repo BTW 👍

**Comment by joychester** [comment]
@alexbardas , let me validate on my side, Thanks a lot for your help, nice repo BTW 👍
