### ISSUE TITLE
Is HAR only available on `end`?

### ISSUE THREAD

**Issue by cheapsteak** [alexbardas/nightmare-har-plugin#2]
Would it be possible to have this data be available whenever it's requested? i.e behave similarly to `.cookies.get/set`?

**Comment by alexbardas** [comment]
HAR data should be available immediately after using `.getHAR()`, for example:
```
nightmare
  .waitForDevtools()
   ...
  .getHAR()
  .then((result) => console.log(JSON.stringify({log: result})))
```
which is similar to the cookies.get api.

Please reopen this issue if this is not the case.
